server:
  port: 8000
spring:
  redis:
    password: root
    host: 192.168.188.146
    port: 6379
  session:
    store-type: redis #\u5B58\u50A8\u65B9\u5F0F
    timeout: 1800 #session\u8FC7\u671F\u65F6\u95F4 \u5355\u4F4D\uFF1A\u79D2
  thymeleaf:  #\u5F00\u59CBthymeleaf\u8BBE\u7F6E
    cache: false #\u7981\u7528\u7F13\u5B58

